export const ACTIONS = {
    JOIN: 'join',
    LEAVE: 'leave',
    ADD_PEER: 'add-peer',
    RELAY_ICE: 'relay-ice',
    RELAY_SDP: 'relay-sdp',
    ICE_CANDIDATE: 'ice-candidate',
    SESSION_DESCRIPTION: 'session-description',
    REMOVE_PEER: 'remove-peer',
    MUTE: 'mute',
    UNMUTE: 'unmute',
    JOIN_REQUEST: 'join-request',
    APPROVE_JOIN_REQUEST: 'approve-join-request',
    JOIN_APPROVED: "join-approved",
    JOIN_CANCELLED: "join-cancelled",
    USER_NOT_ALLOWED: "user-not-allowed",
    REMOVE_USER: "remove-user", 
    YOU_ARE_REMOVED: "you-are-removed",
    // need to implement these actions
    CHECK_USER_IN_ROOM: "check-user-in-room",
    JOIN_REQUEST_PENDING: "join_request_pending",
    USER_ALREADY_IN_ROOM: "user-already-in-room",
    ROOM_NOT_FOUND: "room-not_found",
    ERROR: "error"
}